/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.slickqa.junit.testrunner;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestRunnerTest {
    @Test void appHasAGreeting() {
        TestRunner classUnderTest = new TestRunner();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
